[2024-04-02 01:41:06,001] werkzeug - WARNING -  * Debugger is active!
[2024-04-02 01:41:06,059] werkzeug - INFO -  * Debugger PIN: 432-151-411
[2024-04-02 01:41:33,045] root - INFO - 
        Error occured in script: 
        [ C:\Users\101ri\OneDrive\Desktop\ML\End-to-End ML\MLProject -2\app.py ] at 
        try block line number: [18] and exception block line number: [20] 
        error message: [we are testing custom exception]
        
[2024-04-02 01:41:33,045] root - INFO - lets testing logging info.
[2024-04-02 01:41:33,045] werkzeug - INFO - 127.0.0.1 - - [02/Apr/2024 01:41:33] "GET / HTTP/1.1" 200 -
[2024-04-02 01:41:33,903] werkzeug - INFO - 127.0.0.1 - - [02/Apr/2024 01:41:33] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
[2024-04-02 01:43:04,080] werkzeug - INFO -  * Detected change in 'C:\\Users\\101ri\\OneDrive\\Desktop\\ML\\End-to-End ML\\MLProject -2\\app.py', reloading
[2024-04-02 01:43:04,085] werkzeug - INFO -  * Detected change in 'C:\\Users\\101ri\\OneDrive\\Desktop\\ML\\End-to-End ML\\MLProject -2\\app.py', reloading
